const GET_SELLER = 'GET_SELLER'
const SHOW_DETAIL = 'SHOW_DETAIL'
const HIDE_DETAIL = 'HIDE_DETAIL'
const GET_GOODS = 'GET_GOODS'
const GET_SELLBG = 'GET_SELLBG'
const GET_RATINGS = 'GET_RATINGS'
const FLAGDETAIL = 'FLAGDETAIL'
const GET_ARR = 'GET_ARR'
const FOOD_SHOW = 'FOOD_SHOW'
const FOOD_HIDE = 'FOOD_HIDE'
const CARDETAIL_SHOW = 'CARDETAIL_SHOW'
const CARDETAIL_HIDE = 'CARDETAIL_HIDE'

export default {
	GET_SELLER,
	SHOW_DETAIL,
	HIDE_DETAIL,
	GET_GOODS,
	GET_SELLBG,
	GET_RATINGS,
	FLAGDETAIL,
	GET_ARR,
	FOOD_SHOW,
	FOOD_HIDE,
	CARDETAIL_SHOW,
	CARDETAIL_HIDE
}